### ISSUE TITLE
Getting Delivery Report

### ISSUE THREAD

**Issue by christogonus** [team-telnyx/telnyx-php#72]
I have a system that queues messages in the background.
When a message is sent, the sms_id is stored in database.

Now, I want to be able to call an endpoint at a later time/date to get the delivery report of a message.

Is it covered here?

**Comment by vionash** [comment]
No, delivery reports are sent to you via webhooks. 
You'd have to store those into your database so that you can call them later. 
We don't have an endpoint to check delivery time/date, unless you generate a full MDR Report on the time frame and search the xml  output for the ID that you would save. 

It would be easier to store the time/date when you receive the webhooks and more efficient.
